 ${workspace_loc}/mpsoc/rtl/arbiter.v 
 ${workspace_loc}/mpsoc/rtl/src_noc/fattree.v              
 ${workspace_loc}/mpsoc/rtl/src_noc/route_mesh.v
 ${workspace_loc}/mpsoc/rtl/src_noc/baseline.v               
 ${workspace_loc}/mpsoc/rtl/src_noc/flit_buffer_reg_bas.v
 ${workspace_loc}/mpsoc/rtl/src_noc/router_bypass.sv
 ${workspace_loc}/mpsoc/rtl/src_noc/canonical_credit_count.v
 ${workspace_loc}/mpsoc/rtl/src_noc/flit_buffer.v
 ${workspace_loc}/mpsoc/rtl/src_noc/router.v
 ${workspace_loc}/mpsoc/rtl/src_noc/class_table.v
 ${workspace_loc}/mpsoc/rtl/src_noc/header_flit.v
 ${workspace_loc}/mpsoc/rtl/src_noc/route_torus.v
 ${workspace_loc}/mpsoc/rtl/src_noc/combined_vc_sw_alloc.v
 ${workspace_loc}/mpsoc/rtl/src_noc/inout_ports.v
 ${workspace_loc}/mpsoc/rtl/src_noc/routing.v
 ${workspace_loc}/mpsoc/rtl/src_noc/comb_nonspec.v
 ${workspace_loc}/mpsoc/rtl/src_noc/input_ports.v
 ${workspace_loc}/mpsoc/rtl/src_noc/ss_allocator.v
 ${workspace_loc}/mpsoc/rtl/src_noc/comb-spec1.v
 ${workspace_loc}/mpsoc/rtl/src_noc/iport_reg_base.v
 ${workspace_loc}/mpsoc/rtl/src_noc/test_topology_genvar.v
 ${workspace_loc}/mpsoc/rtl/src_noc/comb_spec2.v
 ${workspace_loc}/mpsoc/rtl/main_comp.v
 ${workspace_loc}/mpsoc/rtl/src_noc/congestion_analyzer.v
 ${workspace_loc}/mpsoc/rtl/src_noc/mesh_torus_noc.v
 ${workspace_loc}/mpsoc/rtl/src_noc/traffic_gen.v
 ${workspace_loc}/mpsoc/rtl/src_noc/credit_count.v
 ${workspace_loc}/mpsoc/rtl/src_noc/mesh_torus_routting.v
 ${workspace_loc}/mpsoc/rtl/src_noc/tree.v
 ${workspace_loc}/mpsoc/rtl/src_noc/crossbar.v
 ${workspace_loc}/mpsoc/rtl/src_noc/mesh_torus.v
 ${workspace_loc}/mpsoc/rtl/src_noc/wrra.v
 ${workspace_loc}/mpsoc/rtl/src_noc/debug.v
 ${workspace_loc}/mpsoc/rtl/src_noc/noc.v
