#!/bin/sh
# $Id: gccrom,v 1.18 2008-05-01 08:35:04 sybreon Exp $

TOOLCHAIN="$PRONOC_WORK/toolchain"


# Compile using C pre-processor

ELFFILE="rom"
XILFLAGS="-mtune=v5.00 -mxl-soft-div -msoft-float -mxl-barrel-shift -mno-xl-soft-mul"
CXXFLAGS="-O1"
LNKFLAGS="-Wl,-defsym -Wl,_STACK_SIZE=${STACK_SIZE} -Wl,-defsym -Wl,_HEAP_SIZE=${HEAP_SIZE}"
LIBFLAGS=""
INCFLAGS="-Icc/"
RAMSIZE="3FFF" #for aeMB ramwith of 12

$TOOLCHAIN/aemb/bin/mb-g++ $XILFLAGS $CXXFLAGS $LNKFLAGS $LIBFLAGS $INCFLAGS -specs=aemb.specs $@ -o $ELFFILE && \
echo "xgcc=$?" && \

# Create a text listing of the compiled code
#$TOOLCHAIN/mb-objdump -DSCz $ELFFILE > $ELFFILE.dump && \
#echo "dump=$?" && \

# Convert the ELF file to an SREC file
#$TOOLCHAIN/mb-objcopy -O srec $ELFFILE $ELFFILE.srec && \
#echo "copy=$?" && \

# Generate a Verilog VMEM file from the SREC file
#srec_cat $ELFFILE.srec -fill 0xFF -within $ELFFILE.srec --range-pad 4 -o out/dump.vmem -vmem 32 && \
#echo "srec=$?" && \


# Convert the ELF file to an IHEX file
$TOOLCHAIN/aemb/bin/mb-objcopy -O ihex $ELFFILE $ELFFILE.ihex && \
#echo "copy2ihex=$?" && \

# Generate a MIF & BIN files from the IHEX file
$TOOLCHAIN/bin/ihex2mif -f $ELFFILE.ihex -e $RAMSIZE -o ram.mif && \
echo "ihex2mif=$?" 
$TOOLCHAIN/bin/ihex2bin -i $ELFFILE.ihex  -o ram.bin && \
echo "ihex2bin=$?" 

$TOOLCHAIN/bin/bin2str -f ram.bin -h   && \
echo "bin2str=$?" 

# echo the checksum
#MD5=$(sha1sum $ELFFILE | cut -c1-32) && \
#echo "sha1=$MD5" 

# Cleanup code
#rm $ELFFILE.srec && rm $ELFFILE
