##-------------------------------------
## LED Status Pinout   (bottom to top)
##-------------------------------------

#set_property PACKAGE_PIN AB8 [get_ports {led[0]}]
#set_property PACKAGE_PIN AA8 [get_ports {led[1]}]
#set_property PACKAGE_PIN AC9 [get_ports {led[2]}]
#set_property PACKAGE_PIN AB9 [get_ports {led[3]}]
#set_property PACKAGE_PIN AE26 [get_ports {led[4]}]
#set_property PACKAGE_PIN G19 [get_ports {led[5]}]
#set_property PACKAGE_PIN E18 [get_ports {led[6]}]
#set_property PACKAGE_PIN F16 [get_ports {led[7]}]

#set_property IOSTANDARD LVCMOS15 [get_ports {led[0]}]
#set_property IOSTANDARD LVCMOS15 [get_ports {led[1]}]
#set_property IOSTANDARD LVCMOS15 [get_ports {led[2]}]
#set_property IOSTANDARD LVCMOS15 [get_ports {led[3]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {led[4]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {led[5]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {led[6]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {led[7]}]

#set_property SLEW SLOW [get_ports {led[7]}]
#set_property SLEW SLOW [get_ports {led[6]}]
#set_property SLEW SLOW [get_ports {led[5]}]
#set_property SLEW SLOW [get_ports {led[4]}]
#set_property SLEW SLOW [get_ports {led[3]}]
#set_property SLEW SLOW [get_ports {led[2]}]
#set_property SLEW SLOW [get_ports {led[1]}]
#set_property SLEW SLOW [get_ports {led[0]}]

#set_property DRIVE 4 [get_ports {led[7]}]
#set_property DRIVE 4 [get_ports {led[6]}]
#set_property DRIVE 4 [get_ports {led[5]}]
#set_property DRIVE 4 [get_ports {led[4]}]
#set_property DRIVE 4 [get_ports {led[3]}]
#set_property DRIVE 4 [get_ports {led[2]}]
#set_property DRIVE 4 [get_ports {led[1]}]
#set_property DRIVE 4 [get_ports {led[0]}]

#-------------
# BUTTON
#------------

#set_property PACKAGE_PIN AA12 [get_ports {button_n}]
#set_property PACKAGE_PIN AB12 [get_ports {button_s}]
#set_property PACKAGE_PIN AC6  [get_ports {button_w}]
#set_property PACKAGE_PIN AG5  [get_ports {button_e}]
#set_property PACKAGE_PIN G12  [get_ports {button_c}]

#set_property IOSTANDARD LVCMOS15 [get_ports {button_n}]
#set_property IOSTANDARD LVCMOS15 [get_ports {button_s}]
#set_property IOSTANDARD LVCMOS15 [get_ports {button_w}]
#set_property IOSTANDARD LVCMOS15 [get_ports {button_e}]
#set_property IOSTANDARD LVCMOS25 [get_ports {button_c}]

#--------------------
# DIP SW
#-------------------

#set_property PACKAGE_PIN Y28  [get_ports {dipsw[3]}]
#set_property PACKAGE_PIN AA28 [get_ports {dipsw[2]}]
#set_property PACKAGE_PIN W29  [get_ports {dipsw[1]}]
#set_property PACKAGE_PIN Y29  [get_ports {dipsw[0]}]

#set_property IOSTANDARD LVCMOS25 [get_ports {dipsw[3]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {dipsw[2]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {dipsw[1]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {dipsw[0]}]

#-----------------------
# CLK
#-----------------------

# on board differential clock, 200MHz
#set_property PACKAGE_PIN AD12 [get_ports clk_p]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports clk_n]
#set_property PACKAGE_PIN AD11 [get_ports clk_n]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports clk_n]



# UART Pins
#set_property PACKAGE_PIN M19 [get_ports rxd]
#set_property IOSTANDARD LVCMOS25 [get_ports rxd]
#set_property PACKAGE_PIN K24 [get_ports txd]
#set_property IOSTANDARD LVCMOS25 [get_ports txd]

# SD/SPI Pins
#set_property PACKAGE_PIN AC21 [get_ports spi_cs]
#set_property IOSTANDARD LVCMOS25 [get_ports spi_cs]
#set_property PACKAGE_PIN AB23 [get_ports spi_sclk]
#set_property IOSTANDARD LVCMOS25 [get_ports spi_sclk]
#set_property PACKAGE_PIN AB22 [get_ports spi_mosi]
#set_property IOSTANDARD LVCMOS25 [get_ports spi_mosi]
#set_property PACKAGE_PIN AC20 [get_ports spi_miso]
#set_property IOSTANDARD LVCMOS25 [get_ports spi_miso]

# JTAG DEBUGGER /* julian pavon rivera::josh m4j0rt0m */
#set_property PACKAGE_PIN AB25 [get_ports tms]
#set_property IOSTANDARD LVCMOS25 [get_ports tms]
#set_property PACKAGE_PIN L25 [get_ports tck]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets tck_IBUF]
#set_property IOSTANDARD LVCMOS25 [get_ports tck]
#set_property PACKAGE_PIN AB28 [get_ports tdo]
#set_property IOSTANDARD LVCMOS25 [get_ports tdo]
#set_property PACKAGE_PIN AA27 [get_ports tdi]
#set_property IOSTANDARD LVCMOS25 [get_ports tdi]

#FMC LA
#set_property PACKAGE_PIN B25 [get_ports FMC_HPC_LA00_CC_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA00_CC_N]
#set_property PACKAGE_PIN C25 [get_ports FMC_HPC_LA00_CC_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA00_CC_P]
#set_property PACKAGE_PIN C26 [get_ports FMC_HPC_LA01_CC_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA01_CC_N]
#set_property PACKAGE_PIN D26 [get_ports FMC_HPC_LA01_CC_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA01_CC_P]
#set_property PACKAGE_PIN H25 [get_ports FMC_HPC_LA02_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA02_N]
#set_property PACKAGE_PIN H24 [get_ports FMC_HPC_LA02_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA02_P]
#set_property PACKAGE_PIN H27 [get_ports FMC_HPC_LA03_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA03_N]
#set_property PACKAGE_PIN H26 [get_ports FMC_HPC_LA03_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA03_P]
#set_property PACKAGE_PIN F28 [get_ports FMC_HPC_LA04_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA04_N]
#set_property PACKAGE_PIN G28 [get_ports FMC_HPC_LA04_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA04_P]
#set_property PACKAGE_PIN F30 [get_ports FMC_HPC_LA05_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA05_N]
#set_property PACKAGE_PIN G29 [get_ports FMC_HPC_LA05_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA05_P]
#set_property PACKAGE_PIN G30 [get_ports FMC_HPC_LA06_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA06_N]
#set_property PACKAGE_PIN H30 [get_ports FMC_HPC_LA06_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA06_P]
#set_property PACKAGE_PIN D28 [get_ports FMC_HPC_LA07_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA07_N]
#set_property PACKAGE_PIN E28 [get_ports FMC_HPC_LA07_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA07_P]
#set_property PACKAGE_PIN E30 [get_ports FMC_HPC_LA08_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA08_N]
#set_property PACKAGE_PIN E29 [get_ports FMC_HPC_LA08_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA08_P]
#set_property PACKAGE_PIN A30 [get_ports FMC_HPC_LA09_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA09_N]
#set_property PACKAGE_PIN B30 [get_ports FMC_HPC_LA09_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA09_P]
#set_property PACKAGE_PIN C30 [get_ports FMC_HPC_LA10_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA10_N]
#set_property PACKAGE_PIN D29 [get_ports FMC_HPC_LA10_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA10_P]
#set_property PACKAGE_PIN F27 [get_ports FMC_HPC_LA11_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA11_N]
#set_property PACKAGE_PIN G27 [get_ports FMC_HPC_LA11_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA11_P]
#set_property PACKAGE_PIN B29 [get_ports FMC_HPC_LA12_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA12_N]
#set_property PACKAGE_PIN C29 [get_ports FMC_HPC_LA12_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA12_P]
#set_property PACKAGE_PIN A26 [get_ports FMC_HPC_LA13_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA13_N]
#set_property PACKAGE_PIN A25 [get_ports FMC_HPC_LA13_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA13_P]
#set_property PACKAGE_PIN A28 [get_ports FMC_HPC_LA14_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA14_N]
#set_property PACKAGE_PIN B28 [get_ports FMC_HPC_LA14_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA14_P]
#set_property PACKAGE_PIN B24 [get_ports FMC_HPC_LA15_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA15_N]
#set_property PACKAGE_PIN C24 [get_ports FMC_HPC_LA15_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA15_P]
#set_property PACKAGE_PIN A27 [get_ports FMC_HPC_LA16_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA16_N]
#set_property PACKAGE_PIN B27 [get_ports FMC_HPC_LA16_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA16_P]
#set_property PACKAGE_PIN E20 [get_ports FMC_HPC_LA17_CC_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA17_CC_N]
#set_property PACKAGE_PIN F20 [get_ports FMC_HPC_LA17_CC_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA17_CC_P]
#set_property PACKAGE_PIN E21 [get_ports FMC_HPC_LA18_CC_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA18_CC_N]
#set_property PACKAGE_PIN F21 [get_ports FMC_HPC_LA18_CC_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA18_CC_P]
#set_property PACKAGE_PIN F18 [get_ports FMC_HPC_LA19_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA19_N]
#set_property PACKAGE_PIN G18 [get_ports FMC_HPC_LA19_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA19_P]
#set_property PACKAGE_PIN D19 [get_ports FMC_HPC_LA20_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA20_N]
#set_property PACKAGE_PIN E19 [get_ports FMC_HPC_LA20_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA20_P]
#set_property PACKAGE_PIN A21 [get_ports FMC_HPC_LA21_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA21_N]
#set_property PACKAGE_PIN A20 [get_ports FMC_HPC_LA21_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA21_P]
#set_property PACKAGE_PIN B20 [get_ports FMC_HPC_LA22_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA22_N]
#set_property PACKAGE_PIN C20 [get_ports FMC_HPC_LA22_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA22_P]
#set_property PACKAGE_PIN A22 [get_ports FMC_HPC_LA23_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA23_N]
#set_property PACKAGE_PIN B22 [get_ports FMC_HPC_LA23_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA23_P]
#set_property PACKAGE_PIN A17 [get_ports FMC_HPC_LA24_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA24_N]
#set_property PACKAGE_PIN A16 [get_ports FMC_HPC_LA24_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA24_P]
#set_property PACKAGE_PIN F17 [get_ports FMC_HPC_LA25_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA25_N]
#set_property PACKAGE_PIN G17 [get_ports FMC_HPC_LA25_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA25_P]
#set_property PACKAGE_PIN A18 [get_ports FMC_HPC_LA26_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA26_N]
#set_property PACKAGE_PIN B18 [get_ports FMC_HPC_LA26_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA26_P]
#set_property PACKAGE_PIN B19 [get_ports FMC_HPC_LA27_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA27_N]
#set_property PACKAGE_PIN C19 [get_ports FMC_HPC_LA27_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA27_P]
#set_property PACKAGE_PIN C16 [get_ports FMC_HPC_LA28_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA28_N]
#set_property PACKAGE_PIN D16 [get_ports FMC_HPC_LA28_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA28_P]
#set_property PACKAGE_PIN B17 [get_ports FMC_HPC_LA29_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA29_N]
#set_property PACKAGE_PIN C17 [get_ports FMC_HPC_LA29_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA29_P]
#set_property PACKAGE_PIN C22 [get_ports FMC_HPC_LA30_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA30_N]
#set_property PACKAGE_PIN D22 [get_ports FMC_HPC_LA30_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA30_P]
#set_property PACKAGE_PIN F22 [get_ports FMC_HPC_LA31_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA31_N]
#set_property PACKAGE_PIN G22 [get_ports FMC_HPC_LA31_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA31_P]
#set_property PACKAGE_PIN C21 [get_ports FMC_HPC_LA32_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA32_N]
#set_property PACKAGE_PIN D21 [get_ports FMC_HPC_LA32_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA32_P]
#set_property PACKAGE_PIN H22 [get_ports FMC_HPC_LA33_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA33_N]
#set_property PACKAGE_PIN H21 [get_ports FMC_HPC_LA33_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_LA33_P]
## FMC HA
#set_property PACKAGE_PIN D13 [get_ports FMC_HPC_HA00_CC_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_HA00_CC_N]
#set_property PACKAGE_PIN D12 [get_ports FMC_HPC_HA00_CC_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_HA00_CC_P]
#set_property PACKAGE_PIN G14 [get_ports FMC_HPC_HA01_CC_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_HA01_CC_N]
#set_property PACKAGE_PIN H14 [get_ports FMC_HPC_HA01_CC_P]
# set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_HA01_CC_P]
#set_property PACKAGE_PIN C11 [get_ports FMC_HPC_HA02_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_HA02_N]
#set_property PACKAGE_PIN D11 [get_ports FMC_HPC_HA02_P]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_HA02_P]
#set_property PACKAGE_PIN B12 [get_ports FMC_HPC_HA03_N]
#set_property IOSTANDARD LVCMOS25 [get_ports FMC_HPC_HA03_N]



#TIME
#jtag clk
#create_clock -period 100.000 -name jtag_clk -waveform {0.000 50.000} -add [get_ports tck]
#main clk
#create_clock -period 5.000 -name ext_clk -waveform {0.000 2.500} -add [get_ports clk_p]
#create_clock -period 5.000 -name asic_clk -waveform {0.000 2.500} -add [get_nets clk_asic]
#create_clock -period 20.000 -name Sysclk_clk -waveform {0.000 10.000} -add [get_nets clk]
#Diferent clock domains
#set_false_path -from [get_clocks asic_clk] -to [get_clocks Sysclk_clk]
#set_false_path -from [get_clocks Sysclk_clk] -to [get_clocks asic_clk]
#set_clock_groups -asynchronous \
#-group {jtag_clk} \
#-group {ext_clk} \
#-group {asic_clk} \
#-group {Sysclk_clk}
